#!/bin/sh
# Apex provider backed by execdev.
#
# apex calls a provider as:
#
#     apex-remote-<provider> DESTINATION COMMAND
#
# where COMMAND is one shell command line. execdev takes an argv vector, so this
# runs the command through a remote login bash to pick up /etc/profile.d setup.

set -eu

if [ "$#" -ne 2 ]; then
    echo "usage: apex-remote-devserver HOST COMMAND" >&2
    exit 64
fi

dest=$1
remote_cmd=$2

execdev=${APEX_EXECDEV:-}
if [ -z "$execdev" ]; then
    if command -v execdev >/dev/null 2>&1; then
        execdev=$(command -v execdev)
    elif [ -x /Users/meriksen/.cargo/bin/execdev ]; then
        execdev=/Users/meriksen/.cargo/bin/execdev
    else
        echo "apex-remote-devserver: execdev not found" >&2
        exit 127
    fi
fi

exec "$execdev" "$dest" -- /bin/bash -l -c "$remote_cmd"
